[project]
name = "stacks-lottery"
description = "Decentralized lottery on Stacks blockchain"
authors = ["serayd61"]
telemetry = false
cache_dir = ".cache"
requirements = []

[contracts.lottery]
path = "contracts/lottery.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]


